services:
  postgres:
    container_name: learn-nestjs-db
    image: postgres:17.5-alpine
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: